"""
Output formatters for different contexts (GitHub, CI, JSON).
"""

import json


def format_json(result: dict) -> str:
    """Format result as JSON."""
    return json.dumps(result, indent=2)


def format_github_comment(result: dict) -> str:
    """Format result as a GitHub PR comment in markdown."""
    if result['status'] == 'success' and not result.get('duplicates'):
        return "✅ **No code duplication detected in this PR**"

    summary = result['summary']
    lines = [
        "## 🔍 Code Duplication Analysis",
        "",
        f"Scanned **{summary.get('total_functions_in_codebase', 'N/A')}** functions, "
        f"**{summary.get('total_changed_functions', 0)}** in this PR.",
        "",
        f"Found **{summary.get('duplicate_count', 0)}** potential duplications:",
        f"- **{summary.get('duplicates_against_existing', 0)}** match existing code",
        f"- **{summary.get('duplicates_within_pr', 0)}** within this PR",
        "",
        "### Clone Types",
        "| Type | Count | Description |",
        "|------|-------|-------------|",
    ]

    clone_types = summary.get('clone_types', {})
    lines.extend([
        f"| T1 | {clone_types.get('T1', 0)} | Exact copy |",
        f"| T2 | {clone_types.get('T2', 0)} | Renamed identifiers |",
        f"| T3 | {clone_types.get('T3', 0)} | Modified statements |",
        f"| T4 | {clone_types.get('T4', 0)} | Semantic similarity |",
        "",
    ])

    duplicates = result.get('duplicates', [])
    if duplicates:
        lines.extend(["### Top Duplications", ""])

        for i, dup in enumerate(duplicates[:5], 1):
            tag = "📁 within PR" if dup.get('within_pr') else "📦 existing"
            lines.extend([
                "<details>",
                f"<summary><b>{i}. {dup['clone_type']}</b> - "
                f"{dup['similarity']:.1%} ({tag})</summary>",
                "",
                f"**New:** `{dup['new_code']['file']}` L{dup['new_code']['lines']}",
                "```cpp",
                dup['new_code']['preview'],
                "```",
                "",
                f"**Match:** `{dup['existing_code']['file']}` L{dup['existing_code']['lines']}",
                "```cpp",
                dup['existing_code']['preview'],
                "```",
                "</details>",
                ""
            ])

    lines.extend([
        "---",
        "*Generated by [Cluain](https://github.com/sloggo/cluain)*"
    ])

    return "\n".join(lines)


def format_ci_output(result: dict) -> str:
    """Format as CI-friendly console output."""
    summary = result.get('summary', {})
    lines = [
        "=== Cluain PR Analysis ===",
        f"Changed functions: {summary.get('total_changed_functions', 0)}",
        f"Codebase functions: {summary.get('total_functions_in_codebase', 'N/A')}",
        f"Duplications found: {summary.get('duplicate_count', 0)}",
        ""
    ]

    duplicates = result.get('duplicates', [])
    if duplicates:
        clone_types = summary.get('clone_types', {})
        type_str = ", ".join(f"{k}={v}" for k, v in clone_types.items() if v > 0)
        lines.append(f"Clone types: {type_str}")
        lines.append("")
        lines.append("Top duplications:")

        for i, dup in enumerate(duplicates[:10], 1):
            lines.append(
                f"  {i}. [{dup['clone_type']}] {dup['similarity']:.1%} | "
                f"{dup['new_code']['file']}:{dup['new_code']['lines']} <-> "
                f"{dup['existing_code']['file']}:{dup['existing_code']['lines']}"
            )

    return "\n".join(lines)


def get_formatter(output_format: str):
    """Get formatter function by name."""
    formatters = {
        'json': format_json,
        'github': format_github_comment,
        'ci': format_ci_output
    }
    return formatters.get(output_format, format_ci_output)
